import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import type { Topic } from '@/data/topics';

export type Language = 'zh' | 'en';

const STORAGE_KEY = 'just-ddl-language';

const topicCopy: Record<string, Record<Language, { name: string; description: string }>> = {
  'hackathon-ddl': {
    zh: { name: '黑客松', description: '全球黑客松赛事与截稿日期追踪，覆盖 Devpost、MLH、DoraHacks、ETHGlobal 等平台。' },
    en: { name: 'Hackathon', description: 'Global hackathon deadlines across Devpost, MLH, DoraHacks, ETHGlobal, and independent event boards.' },
  },
  'agent-ddl': {
    zh: { name: 'AI 智能体', description: 'AI Agent 竞赛、评测榜单与应用挑战，一站式追踪 LLM 智能体生态。' },
    en: { name: 'AI Agent', description: 'AI agent hackathons, benchmark tracks, leaderboard windows, and applied LLM agent challenges.' },
  },
  'cv-ddl': {
    zh: { name: '计算机视觉', description: '计算机视觉会议、挑战赛与 workshop 截止日，覆盖 CVPR、ICCV、ECCV、WACV 等。' },
    en: { name: 'Computer Vision', description: 'Computer vision conferences, challenge tracks, workshops, and benchmark deadlines.' },
  },
  'nlp-ddl': {
    zh: { name: '自然语言处理', description: 'NLP 会议、shared task 与评测挑战，覆盖 ACL、EMNLP、NAACL、COLING 等。' },
    en: { name: 'NLP', description: 'NLP conferences, shared tasks, evaluation tracks, and workshop deadlines.' },
  },
  'academic-ddl': {
    zh: { name: '学术科研', description: '跨学科学术会议、基金申请、暑校与科研项目截止日。' },
    en: { name: 'Academic', description: 'Cross-discipline academic conferences, grant windows, summer schools, and research programs.' },
  },
  'journal-ddl': {
    zh: { name: '期刊专题', description: '期刊 Special Issue、Special Section、专题征稿与 Call for Papers 截止日。' },
    en: { name: 'Journal CFP', description: 'Journal special issues, special sections, topical calls, and call-for-papers deadlines.' },
  },
  'programming-ddl': {
    zh: { name: '编程竞赛', description: '算法竞赛、编程挑战、训练营和开发者赛事，覆盖 ICPC、Codeforces、AtCoder 等。' },
    en: { name: 'Programming', description: 'Competitive programming contests, coding challenges, training camps, and developer events.' },
  },
  'holiday-ddl': {
    zh: { name: '节假日', description: '法定节假日、二十四节气、传统节日、国际纪念日和海外公共假日倒计时。' },
    en: { name: 'Holidays', description: 'Public holidays, the 24 solar terms, traditional festivals, international observances, and global holiday countdowns.' },
  },
  'multimodal-ddl': {
    zh: { name: '多模态', description: '多模态理解、VLM、AIGC、视频和音频评测挑战截止日。' },
    en: { name: 'Multimodal', description: 'Multimodal understanding, VLM, AIGC, video, and audio evaluation challenge deadlines.' },
  },
  'security-ddl': {
    zh: { name: '安全与 CTF', description: 'CTF、网络安全会议、漏洞赏金、攻防演练和安全研究专题截止日。' },
    en: { name: 'Security & CTF', description: 'CTF, cybersecurity conferences, bug bounty windows, red-team drills, and security research deadlines.' },
  },
  'data-science-ddl': {
    zh: { name: '数据科学', description: 'Kaggle、天池、DataCastle、数据挖掘会议与数据挑战赛截止日。' },
    en: { name: 'Data Science', description: 'Kaggle, Tianchi, DataCastle, data mining conferences, and data challenge deadlines.' },
  },
  'open-source-ddl': {
    zh: { name: '开源计划', description: 'GSoC、OSPP、LFX、Outreachy、开源实习与社区贡献计划截止日。' },
    en: { name: 'Open Source', description: 'GSoC, OSPP, LFX, Outreachy, open-source internships, and community program deadlines.' },
  },
  'robotics-ddl': {
    zh: { name: '机器人', description: '机器人竞赛、ICRA/IROS challenge、自动驾驶和具身智能评测节点。' },
    en: { name: 'Robotics', description: 'Robotics competitions, ICRA/IROS challenges, autonomous driving, and embodied AI evaluation windows.' },
  },
  'startup-ddl': {
    zh: { name: '创业与孵化', description: '创业大赛、加速器申请、创新创业项目、路演和 grant 申请截止日。' },
    en: { name: 'Startup', description: 'Startup competitions, accelerator applications, innovation programs, demo days, and grant deadlines.' },
  },
  'design-ddl': {
    zh: { name: '设计与产品', description: 'UX、产品设计、服务设计、交互设计、工业设计和创意挑战赛截止日。' },
    en: { name: 'Design & Product', description: 'UX, product design, service design, interaction design, industrial design, and creative challenge deadlines.' },
  },
  'exam-ddl': {
    zh: { name: '考试考证', description: '升学考试、语言考试、职业资格、报名缴费和准考证打印提醒。' },
    en: { name: 'Exams', description: 'Academic exams, language tests, professional certificates, registration windows, and admit-card reminders.' },
  },
  'ielts-toefl-ddl': {
    zh: { name: '雅思托福', description: '雅思、托福报名入口、考期发布和官方考试安排追踪。' },
    en: { name: 'IELTS & TOEFL', description: 'IELTS and TOEFL registration portals, test-date releases, and official exam schedule checkpoints.' },
  },
  'scholarship-ddl': {
    zh: { name: '奖学金申请', description: '奖学金、访问学者、暑研、交换项目、博士申请和 fellowship 截止日。' },
    en: { name: 'Scholarships', description: 'Scholarships, visiting programs, summer research, exchange programs, PhD applications, and fellowships.' },
  },
  'civil-service-ddl': {
    zh: { name: '考公考编', description: '公务员、事业单位、选调生、遴选和基层项目报名、笔试、面试节点追踪。' },
    en: { name: 'Civil Service', description: 'Civil service, public institution, selected graduate, public selection, and grassroots program checkpoints.' },
  },
  'game-dev-ddl': {
    zh: { name: '游戏开发', description: 'Game Jam、独立游戏节、学生游戏竞赛、引擎挑战和作品提交截止日。' },
    en: { name: 'Game Dev', description: 'Game jams, indie festivals, student game competitions, engine challenges, and submission deadlines.' },
  },
  'game-ddl': {
    zh: { name: '电竞赛事', description: '英雄联盟、王者荣耀、VALORANT、Dota 2、CS2 与电竞世界杯等赛事赛历和报名/开赛节点。' },
    en: { name: 'Esports', description: 'League of Legends, Honor of Kings, VALORANT, Dota 2, CS2, Esports World Cup, and esports calendar checkpoints.' },
  },
  'game-version-ddl': {
    zh: { name: '游戏版本', description: '英雄联盟、云顶之弈等游戏版本、补丁和赛季更新时间倒计时。' },
    en: { name: 'Game Versions', description: 'Game version, patch, and season update countdowns for League of Legends, Teamfight Tactics, and more.' },
  },
  'concert-ddl': {
    zh: { name: '演唱会', description: '演唱会、巡演、官方场馆活动和开票/演出日期倒计时。' },
    en: { name: 'Concerts', description: 'Concert, tour, official venue event, ticketing, and show-date countdowns.' },
  },
  'movie-tv-ddl': {
    zh: { name: '电影电视剧', description: '电影、电视剧、流媒体和动画上映/上线日期倒计时。' },
    en: { name: 'Movies & TV', description: 'Movie, TV, streaming, and animation release-date countdowns.' },
  },
  'phone-launch-ddl': {
    zh: { name: '手机发布', description: '手机发布会、移动生态发布窗口和官方品牌 source board。' },
    en: { name: 'Phone Launches', description: 'Phone launch events, mobile ecosystem launch windows, and official brand source boards.' },
  },
  'car-launch-ddl': {
    zh: { name: '汽车发布', description: '汽车发布、官方车展、媒体日和新车/出行产品发布窗口。' },
    en: { name: 'Car Launches', description: 'Car launches, official auto shows, media days, and vehicle/mobility product launch windows.' },
  },
  'regulation-ddl': {
    zh: { name: '新规实施', description: '新规实施、强制性标准、监管合规和政策生效日期追踪。' },
    en: { name: 'Regulations', description: 'Effective dates for regulations, mandatory standards, compliance rules, and policy rollouts.' },
  },
  'student-contest-ddl': {
    zh: { name: '学生竞赛', description: '大学生/研究生竞赛、工程挑战、科研项目和作品提交节点。' },
    en: { name: 'Student Contests', description: 'Undergraduate and graduate student competitions, engineering challenges, research projects, and submission checkpoints.' },
  },
  'career-fair-ddl': {
    zh: { name: '招聘会', description: '高校招聘会、实习招聘会、工程/STEM/综合 career fair 日期追踪。' },
    en: { name: 'Career Fairs', description: 'University career fairs, internship fairs, engineering/STEM events, and campus recruiting checkpoints.' },
  },
  'biotech-ddl': {
    zh: { name: '生命科学', description: '生物医药、医学影像、基因组、蛋白质设计和健康 AI 挑战截止日。' },
    en: { name: 'Biotech', description: 'Biomedical, medical imaging, genomics, protein design, and health AI challenge deadlines.' },
  },
  'sports-ddl': {
    zh: { name: '体育赛事', description: '体育赛事、报名节点和赛历倒计时，覆盖乒乓球、羽毛球、篮球、台球、匹克球、马拉松与田径。' },
    en: { name: 'Sports', description: 'Sports event countdowns across table tennis, badminton, basketball, billiards, pickleball, marathons, and athletics.' },
  },
};

const categoryCopy: Record<string, Record<Language, string>> = {
  全部: { zh: '全部', en: 'All' },
  技术赛事: { zh: '技术赛事', en: 'Tech Events' },
  学术科研: { zh: '学术科研', en: 'Research' },
  学术期刊: { zh: '学术期刊', en: 'Journals' },
  专业竞赛: { zh: '专业竞赛', en: 'Competitions' },
  日常通用: { zh: '日常通用', en: 'Everyday' },
  安全开源: { zh: '安全开源', en: 'Security & Open Source' },
  产业创业: { zh: '产业创业', en: 'Startup' },
  设计创作: { zh: '设计创作', en: 'Design & Creation' },
  考试申请: { zh: '考试申请', en: 'Exams & Applications' },
  生命健康: { zh: '生命健康', en: 'Life & Health' },
  体育赛事: { zh: '体育赛事', en: 'Sports' },
  电竞赛事: { zh: '电竞赛事', en: 'Esports' },
  文娱生活: { zh: '文娱生活', en: 'Entertainment' },
  消费发布: { zh: '消费发布', en: 'Consumer Launches' },
  公共生活: { zh: '公共生活', en: 'Public Life' },
  教育职业: { zh: '教育职业', en: 'Education & Career' },
};

const tagCopy: Record<string, Record<Language, string>> = {
  coding: { zh: '编程', en: 'coding' },
  team: { zh: '组队', en: 'team' },
  conference: { zh: '会议', en: 'conference' },
  grant: { zh: '基金', en: 'grant' },
  paper: { zh: '论文', en: 'paper' },
  festival: { zh: '节日', en: 'festival' },
  'solar-term': { zh: '节气', en: 'solar term' },
  vacation: { zh: '假期', en: 'vacation' },
  journal: { zh: '期刊', en: 'journal' },
  'special issue': { zh: '专题', en: 'special issue' },
  'table tennis': { zh: '乒乓球', en: 'table tennis' },
  badminton: { zh: '羽毛球', en: 'badminton' },
  marathon: { zh: '马拉松', en: 'marathon' },
  basketball: { zh: '篮球', en: 'basketball' },
  billiards: { zh: '台球', en: 'billiards' },
  pickleball: { zh: '匹克球', en: 'pickleball' },
  'League of Legends': { zh: '英雄联盟', en: 'League of Legends' },
  王者荣耀: { zh: '王者荣耀', en: 'Honor of Kings' },
  VALORANT: { zh: 'VALORANT', en: 'VALORANT' },
  CS2: { zh: 'CS2', en: 'CS2' },
  'Dota 2': { zh: 'Dota 2', en: 'Dota 2' },
  'game update': { zh: '游戏更新', en: 'game update' },
  patch: { zh: '补丁', en: 'patch' },
  'Teamfight Tactics': { zh: '云顶之弈', en: 'Teamfight Tactics' },
  concert: { zh: '演唱会', en: 'concert' },
  live: { zh: '现场', en: 'live' },
  ticketing: { zh: '开票', en: 'ticketing' },
  movie: { zh: '电影', en: 'movie' },
  TV: { zh: '电视剧', en: 'TV' },
  release: { zh: '上映/发布', en: 'release' },
  smartphone: { zh: '手机', en: 'smartphone' },
  launch: { zh: '发布', en: 'launch' },
  mobile: { zh: '移动设备', en: 'mobile' },
  car: { zh: '汽车', en: 'car' },
  'auto show': { zh: '车展', en: 'auto show' },
  'vehicle launch': { zh: '新车发布', en: 'vehicle launch' },
  regulation: { zh: '新规', en: 'regulation' },
  standard: { zh: '标准', en: 'standard' },
  'effective date': { zh: '实施日', en: 'effective date' },
  compliance: { zh: '合规', en: 'compliance' },
  'student competition': { zh: '学生竞赛', en: 'student competition' },
  graduate: { zh: '研究生', en: 'graduate' },
  research: { zh: '科研', en: 'research' },
  'career fair': { zh: '招聘会', en: 'career fair' },
  internship: { zh: '实习', en: 'internship' },
  'graduate students': { zh: '研究生求职', en: 'graduate students' },
  IELTS: { zh: '雅思', en: 'IELTS' },
  TOEFL: { zh: '托福', en: 'TOEFL' },
  'language test': { zh: '语言考试', en: 'language test' },
  公务员: { zh: '公务员', en: 'civil service' },
  事业单位: { zh: '事业单位', en: 'public institution' },
  选调生: { zh: '选调生', en: 'selected graduates' },
  国考: { zh: '国考', en: 'national exam' },
  报名: { zh: '报名', en: 'registration' },
  遴选: { zh: '遴选', en: 'public selection' },
  选调: { zh: '选调', en: 'selection' },
  招聘: { zh: '招聘', en: 'recruitment' },
};

const dictionary = {
  zh: {
    nav: { plaza: '主题广场', my: '我的 DDL', contribute: '接入专题', about: '关于', github: 'GitHub', repo: '仓库' },
    network: {
      roadmap: '路线图',
      topics: ['黑客松', '智能体', '视觉', 'NLP', '学术', '期刊', '编程', '节假日', '多模态', '安全', '数据', '开源', '机器人', '创业', '设计', '考试', '雅思托福', '奖学金', '考公考编', '游戏开发', '生命科学', '体育', '电竞', '游戏版本', '演唱会', '电影电视剧', '手机发布', '汽车发布', '新规实施', '学生竞赛', '招聘会'],
    },
    home: {
      title: '主题广场',
      heroLine: '把分散在世界各地的截止日，整理成可以订阅、追踪、部署和复用的专题矿场。',
      heroCopy: '默认中文浏览，英文界面需要手动切换。每个专题都拥有独立仓库、独立 Pages、独立 Actions 数据流，后续也能单独接入小程序。',
      activeDeadlines: '活跃截止日',
      topics: '专题',
      totalDeadlines: 'DDL 条目',
      categories: '分类',
      searchPlaceholder: '搜索专题、仓库或关键词...',
      featuredTitle: '正在运行的专题网络',
      featuredCopy: '数据量更大、近期节点更多的专题会优先浮出，方便把 Just-DDL 当成总入口来用。',
      plazaTitle: '全部专题',
      subscribedTitle: '已订阅专题',
      noResults: '没有找到匹配的专题',
      ctaTitle: '已经准备好接入你的专题？',
      ctaCopy: '请在 PR 中写清专题名、仓库地址、GitHub Pages 地址、数据出口、分类和标签。Hub 合并后负责展示和导航，专题数据继续由你的独立仓库维护。',
      ctaAction: '提交注册 PR',
      liveBoard: '部署与数据看板',
      live: '在线',
      sources: '数据源',
      next: '下一条',
      manualLanguage: '英文界面需要手动切换',
      repoModel: '一专题一仓库',
      dataFlow: 'Actions 自动更新',
    },
    topicCard: {
      repo: '仓库',
      pages: '专题站',
      open: '进入专题',
      active: '活跃',
      total: '总计',
      sources: '来源',
      next: '下一条',
      published: '在线',
      demo: '筹备中',
      subscribe: '收藏专题',
      subscribed: '已收藏专题',
      noUpcoming: '暂无进行中',
    },
    detail: {
      back: '主题广场',
      missing: '专题不存在',
      subscribe: '收藏专题',
      subscribed: '已收藏专题',
      repo: 'GitHub 仓库',
      pages: 'GitHub Pages',
      active: '进行中',
      total: '总计',
      next: '下一条',
      sources: '来源',
      allDeadlines: '全部截止日',
      empty: '暂无数据',
      published: '在线',
      demo: '筹备中',
      sportsPlazaTitle: '体育子专题小广场',
      sportsPlazaCopy: '乒乓球、羽毛球、篮球、台球、匹克球、路跑与田径拆成可折叠小专题；pin 住后可以优先展开，后续也能接到个人主页。',
      gamePlazaTitle: '电竞子专题小广场',
      gamePlazaCopy: '英雄联盟、王者荣耀、VALORANT、CS2、Dota 2 和综合电竞拆成可折叠小专题；pin 住后可以优先展开。',
      sportSubtopic: '子专题',
      pinSubtopic: 'Pin 子专题',
      pinnedSubtopic: '已 Pin',
      expand: '展开',
      collapse: '收起',
      events: '条事件',
      vividMode: 'Vivid',
      simpleMode: 'Simple',
    },
    my: {
      title: '我的 DDL',
      summary: '已订阅',
      topics: '个专题',
      individual: '单独收藏',
      personal: '个人添加',
      items: '个 DDL',
      pageHint: '下方统一展示三类内容：收藏专题带来的事件、单独收藏的事件、个人添加的 DDL；个人 DDL 只保存在当前浏览器。',
      organizeLabel: '组织方式',
      displayLabel: '展示方式',
      byTopic: '按专题折叠',
      byTime: '按时间交叉',
      byName: '按名称交叉',
      listView: '长卡列表',
      gridView: '多列卡片',
      displayHint: '长卡适合扫详情，多列卡片适合快速看大量倒计时。',
      topicModeHint: '每个专题是一组，可折叠查看里面的事件。',
      flatModeHint: '不同专题的事件会按当前规则交叉显示。',
      topicPinned: '专题已收藏',
      singleSaved: '单条收藏',
      events: '条事件',
      unknownTopic: '未知专题',
      noActiveInTopic: '这个专题暂无进行中的事件',
      emptyTitle: '还没有订阅任何内容',
      emptyCopy: '去主题广场订阅你关心的领域',
      browse: '浏览主题广场',
      active: '进行中',
      ended: '已结束',
      customTitle: '自定义个人 DDL',
      customHeadline: '添加自己的课程、项目、答辩或生活节点',
      customCopy: '本地保存个人截止日',
      customNote: '仅保存在当前浏览器；换设备前可导出 JSON 备份。',
      personalTopic: '个人DDL',
      personalCategory: '本地',
      localOnly: '本地',
      customTitleLabel: '标题',
      customTitlePlaceholder: '例如：论文终稿提交',
      customDeadlineLabel: '截止时间',
      customCategoryLabel: '分类',
      customCategoryPlaceholder: '个人 / 学业 / 工作',
      customLocationLabel: '地点',
      customLocationPlaceholder: '本地 / Online / 学校',
      customTagsLabel: '标签',
      customTagsPlaceholder: '答辩, 论文, 项目',
      customUrlLabel: '链接',
      customUrlPlaceholder: '可选',
      customDescLabel: '备注',
      customDescPlaceholder: '可选，写给自己看的说明',
      addCustom: '添加',
      updateCustom: '更新',
      editCustom: '编辑',
      deleteCustom: '删除',
      cancelEdit: '取消编辑',
      editingCustom: '正在编辑个人 DDL',
      customAdded: '已添加到我的 DDL',
      customUpdated: '已更新个人 DDL',
      customDeleted: '已删除个人 DDL',
      customInvalid: '请填写标题和有效截止时间',
      exportJson: '导出 JSON',
      importJson: '导入 JSON',
      pinHome: '固定我的 DDL',
      pinHomeShareText: '打开我的 Just-DDL 关注面板',
      pinHomeCopied: '已复制我的 DDL 入口；可加入书签或设为浏览器首页。',
      pinHomeFailed: '无法自动复制，请手动收藏当前页面。',
      importInvalid: 'JSON 格式不正确',
      importedPrefix: '已导入 ',
      importedSuffix: ' 条个人 DDL',
    },
    about: {
      title: '关于 Just DDL',
      intro: 'Just DDL 是一个纯截止日期追踪平台，采用一专题一仓库的开放架构，帮助学生、科研人员、开发者不再错过重要节点。',
      features: '产品特性',
      architecture: '架构设计',
      permissions: '功能权限说明',
      repoAction: 'GitHub 仓库',
      openSource: 'Just DDL 是开源项目，欢迎贡献代码和数据。',
    },
    ddl: {
      ended: '已结束',
      official: '官方链接',
      subscribe: '收藏',
      subscribed: '已收藏',
      awaitingNotice: '待官方公告',
    },
    footer: {
      line: 'Just DDL · 专注每一个截止日 · 社区驱动维护',
      miniProgram: '微信小程序版本即将上线，敬请期待',
      disclaimer: '数据仅供参考，请以官方信息为准',
    },
  },
  en: {
    nav: { plaza: 'Topic Plaza', my: 'My DDL', contribute: 'Add Topic', about: 'About', github: 'GitHub', repo: 'Repo' },
    network: {
      roadmap: 'Roadmap',
      topics: ['Hackathon', 'Agent', 'CV', 'NLP', 'Academic', 'Journal', 'Programming', 'Holiday', 'Multimodal', 'Security', 'Data', 'Open Source', 'Robotics', 'Startup', 'Design', 'Exams', 'IELTS & TOEFL', 'Scholarships', 'Civil Service', 'Game Dev', 'Biotech', 'Sports', 'Esports', 'Game Versions', 'Concerts', 'Movies & TV', 'Phone Launches', 'Car Launches', 'Regulations', 'Student Contests', 'Career Fairs'],
    },
    home: {
      title: 'Topic Plaza',
      heroLine: 'A curated deadline plaza for competitions, research calls, holidays, and planning workflows.',
      heroCopy: 'Chinese is the default. Switch to English manually when needed. Each topic keeps its own repository, Pages site, Actions crawler, validator, and publishing lane.',
      activeDeadlines: 'active deadlines',
      topics: 'topics',
      totalDeadlines: 'DDL items',
      categories: 'categories',
      searchPlaceholder: 'Search topics, repositories, or keywords...',
      featuredTitle: 'Live Topic Network',
      featuredCopy: 'The busiest topics surface first, making Just-DDL feel like the operating center for the whole network.',
      plazaTitle: 'All Topics',
      subscribedTitle: 'Subscribed topics',
      noResults: 'No matching topics',
      ctaTitle: 'Ready to connect your topic?',
      ctaCopy: 'Include the topic name, repository URL, GitHub Pages URL, data export, category, and tags in the PR. After merge, the Hub handles discovery while your repository keeps owning the data.',
      ctaAction: 'Open registration PR',
      liveBoard: 'Deployment and Data Board',
      live: 'live',
      sources: 'sources',
      next: 'next',
      manualLanguage: 'English is a manual switch',
      repoModel: 'one topic, one repo',
      dataFlow: 'Actions auto update',
    },
    topicCard: {
      repo: 'Repository',
      pages: 'Topic site',
      open: 'Open topic',
      active: 'active',
      total: 'total',
      sources: 'sources',
      next: 'next',
      published: 'live',
      demo: 'preparing',
      subscribe: 'Save topic',
      subscribed: 'Topic saved',
      noUpcoming: 'No active item',
    },
    detail: {
      back: 'Topic Plaza',
      missing: 'Topic not found',
      subscribe: 'Save topic',
      subscribed: 'Topic saved',
      repo: 'GitHub Repository',
      pages: 'GitHub Pages',
      active: 'Active',
      total: 'Total',
      next: 'Next',
      sources: 'Sources',
      allDeadlines: 'All deadlines',
      empty: 'No data yet',
      published: 'live',
      demo: 'preparing',
      sportsPlazaTitle: 'Sports Subtopic Plaza',
      sportsPlazaCopy: 'Table tennis, badminton, basketball, billiards, pickleball, running, and athletics are grouped into collapsible mini topics. Pin one to keep it opened first.',
      gamePlazaTitle: 'Esports Subtopic Plaza',
      gamePlazaCopy: 'League of Legends, Honor of Kings, VALORANT, CS2, Dota 2, and multi-title esports are grouped into collapsible mini topics. Pin one to keep it opened first.',
      sportSubtopic: 'Subtopic',
      pinSubtopic: 'Pin subtopic',
      pinnedSubtopic: 'Pinned',
      expand: 'Expand',
      collapse: 'Collapse',
      events: 'events',
      vividMode: 'Vivid',
      simpleMode: 'Simple',
    },
    my: {
      title: 'My DDL',
      summary: 'Subscribed to',
      topics: 'topics',
      individual: 'and saved',
      personal: 'plus',
      items: 'DDL items',
      pageHint: 'This page merges three sources: events from saved topics, individually saved events, and personal DDL. Personal DDL stays in this browser.',
      organizeLabel: 'Organize by',
      displayLabel: 'Display as',
      byTopic: 'Topic groups',
      byTime: 'Time order',
      byName: 'Name order',
      listView: 'Long list',
      gridView: 'Card grid',
      displayHint: 'Long cards are better for details; grid cards make large countdown sets easier to scan.',
      topicModeHint: 'Each topic becomes a collapsible group with its own saved events.',
      flatModeHint: 'Items from different topics are interleaved by the selected rule.',
      topicPinned: 'Topic saved',
      singleSaved: 'Single saves',
      events: 'events',
      unknownTopic: 'Unknown topic',
      noActiveInTopic: 'No active events in this topic',
      emptyTitle: 'Nothing subscribed yet',
      emptyCopy: 'Go to the Topic Plaza and subscribe to the areas you care about',
      browse: 'Browse Topic Plaza',
      active: 'Active',
      ended: 'Ended',
      customTitle: 'Custom personal DDL',
      customHeadline: 'Add coursework, project, defense, or life milestones',
      customCopy: 'Local personal deadlines',
      customNote: 'Saved only in this browser. Export JSON before switching devices.',
      personalTopic: 'Personal DDL',
      personalCategory: 'Local',
      localOnly: 'local',
      customTitleLabel: 'Title',
      customTitlePlaceholder: 'e.g. Final thesis submission',
      customDeadlineLabel: 'Deadline',
      customCategoryLabel: 'Category',
      customCategoryPlaceholder: 'Personal / Study / Work',
      customLocationLabel: 'Location',
      customLocationPlaceholder: 'Local / Online / Campus',
      customTagsLabel: 'Tags',
      customTagsPlaceholder: 'thesis, project, defense',
      customUrlLabel: 'Link',
      customUrlPlaceholder: 'Optional',
      customDescLabel: 'Note',
      customDescPlaceholder: 'Optional personal note',
      addCustom: 'Add',
      updateCustom: 'Update',
      editCustom: 'Edit',
      deleteCustom: 'Delete',
      cancelEdit: 'Cancel edit',
      editingCustom: 'Editing personal DDL',
      customAdded: 'Added to My DDL',
      customUpdated: 'Personal DDL updated',
      customDeleted: 'Personal DDL deleted',
      customInvalid: 'Add a title and a valid deadline',
      exportJson: 'Export JSON',
      importJson: 'Import JSON',
      pinHome: 'Pin My DDL',
      pinHomeShareText: 'Open my Just-DDL watch panel',
      pinHomeCopied: 'My DDL link copied. Save it as a bookmark or browser homepage.',
      pinHomeFailed: 'Unable to copy automatically. Please bookmark this page manually.',
      importInvalid: 'Invalid JSON file',
      importedPrefix: 'Imported ',
      importedSuffix: ' personal DDL items',
    },
    about: {
      title: 'About Just DDL',
      intro: 'Just DDL is a pure deadline tracking platform with an open one-topic-one-repo architecture for students, researchers, and developers.',
      features: 'Product Features',
      architecture: 'Architecture',
      permissions: 'Capability Notes',
      repoAction: 'GitHub Repository',
      openSource: 'Just DDL is open source. Code and data contributions are welcome.',
    },
    ddl: {
      ended: 'Ended',
      official: 'Official link',
      subscribe: 'Save',
      subscribed: 'Saved',
      awaitingNotice: 'Awaiting notice',
    },
    footer: {
      line: 'Just DDL · Every deadline in focus · Community-maintained',
      miniProgram: 'WeChat Mini Program version is coming soon. Stay tuned.',
      disclaimer: 'Data is for reference only; always verify with the official source.',
    },
  },
} as const;

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  copy: typeof dictionary.zh | typeof dictionary.en;
  topicName: (topic: Topic) => string;
  topicDescription: (topic: Topic) => string;
  categoryName: (category: string) => string;
  tagName: (tag: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      return localStorage.getItem(STORAGE_KEY) === 'en' ? 'en' : 'zh';
    } catch {
      return 'zh';
    }
  });

  const setLanguage = (next: Language) => {
    setLanguageState(next);
    try {
      localStorage.setItem(STORAGE_KEY, next);
    } catch {
      /* localStorage can be unavailable in restricted browsers */
    }
  };

  useEffect(() => {
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en';
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    copy: dictionary[language],
    topicName: (topic) => topicCopy[topic.id]?.[language]?.name || topic.name,
    topicDescription: (topic) => topicCopy[topic.id]?.[language]?.description || topic.description,
    categoryName: (category) => categoryCopy[category]?.[language] || category,
    tagName: (tag) => tagCopy[tag]?.[language] || tag,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}



